feat: add optional path to pck json

diff --git a/docker/build-canister b/docker/build-canister
--- a/docker/build-canister
+++ b/docker/build-canister
@@ -9,7 +9,8 @@ function build_canister() {
     local with_certification=$5
     local build_type=$6
     local target=$7
-    shift 7
+    local package_json_path="${8:-$output_dir/$canister.package.json}"
+    shift 8
     local extra_build_args=("$@")
 
     if [ -z "$canister" ]; then
@@ -30,6 +31,11 @@ function build_canister() {
     if [ ! -d "$output_dir" ]; then
         echo "ERROR: The output directory '$output_dir' does not exist."
         exit 1
+    fi
+
+    if [[ ! -f "$package_json_path" ]]; then
+      echo "ERROR: metadata file not found at $package_json_path"
+      exit 1
     fi
 
     TARGET="wasm32-unknown-unknown"
@@ -106,12 +112,7 @@ function build_canister() {
       # This file contains metadata about the build such as name, version, and dependencies.
       # The presence of dependencies indicates that the module is not stock, but extended—
       # either from the satellite (e.g., serverless functions in Rust) or from Sputnik (e.g., serverless functions in JavaScript).
-      if [[ ! -f "$output_dir/$canister.package.json" ]]; then
-        echo "ERROR: metadata file not found at $output_dir/$canister.did"
-        exit 1
-      fi
-
-      ic-wasm "$output_dir/$canister.wasm" -o "$output_dir/$canister.wasm" metadata juno:package -f "$output_dir/$canister.package.json" -v public --keep-name-section
+      ic-wasm "$output_dir/$canister.wasm" -o "$output_dir/$canister.wasm" metadata juno:package -f "$package_json_path" -v public --keep-name-section
 
       if [ -n "$build_type" ]
       then
